apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: inference-gateway-tls
  namespace: opendatahub
spec:
  secretName: inference-gateway-tls-cert
  duration: 2160h  # 90 days
  renewBefore: 360h  # 15 days

  issuerRef:
    name: opendatahub-ca-issuer
    kind: ClusterIssuer

  commonName: inference-gateway.opendatahub.svc.cluster.local

  dnsNames:
  - inference-gateway.opendatahub.svc.cluster.local
  - "*.llm-d-inference-scheduling.svc.cluster.local"

  # Include Gateway external IP if available
  # Update after deployment with: kubectl patch certificate ...
  ipAddresses:
  - 34.7.208.8

  usages:
  - digital signature
  - key encipherment
  - server auth
